name: Promote services

on:
  workflow_dispatch:
    inputs:
      promote_environments:
        type: choice
        description: Choose environments
        required: true
        options:
          - dev to test
          - test to qa
          - qa to prod
      services:
        description: Service names seperated by comma (use ALL for any service or CONFIG_ONLY for configuration updates)
        required: true
        default: service1, service2, service3
      ado-work-item-nbr:
        description: ADO work item number
        required: true
      branch:
        description: Branch to promote in (use none to create new branch)
        required: false
        default: none
env:
  PROMOTE_ENVIRONMENTS: ${{ github.event.inputs.promote_environments }}
  SERVICES: ${{github.event.inputs.services}}
  STORY: ${{github.event.inputs.ado-work-item-nbr}}

jobs:
  promote_service:
    runs-on: ubuntu-latest

    steps:
      # - name: checkout-code
      #   uses: actions/checkout@v4
      #   with:
      #     token: ${{ secrets.TEAM_GITHUB_TOKEN }}
      #     fetch-depth: 0

      - name: Clone repository, create branch, add file, and push
        run: |
          # Set variables
          #REPO_URL="https://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@github.com/aarifmohd1/devops.git"
          git clone https://x-access-token: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@github.com/aarifmohd1/devops.git devops
          NEW_BRANCH="feature-branch"
          
          # # Clone the repository using the token
          # git clone $REPO_URL repo
          # cd repo
          
          # Create a new branch and switch to it
          git checkout -b $NEW_BRANCH
          
          # Create a new file
          echo "This is a test file." > abc.txt
          
          # Add, commit, and push changes
          git add abc.txt
          git commit -m "Added abc.txt"
          git push origin $NEW_BRANCH
        env:
          GITHUB_TOKEN: ${{ secrets.TEAM_GITHUB_TOKEN }}
      # - name: Setup Python script
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.11

      # - name: install-dependencies
      #   run: |
      #     pip install -r $GITHUB_WORKSPACE/promote-scripts/requirements.txt

      # - name: run-promote-script
      #   run: |
      #     maincommit=$(git rev-parse main)
      #     branchcommit=$(git rev-parse HEAD)
      #     export BRANCH_COMMITS=$(git log --pretty="format:%ai;%s" $maincommit..$branchcommit --)

      #     echo "1 $maincommit"
      #     echo "2 $branchcommit"
      #     echo "3 $BRANCH_COMMITS"


      #     set +e
      #     python $GITHUB_WORKSPACE/promote-scripts/promote.py > script.log
      #     res=$?
      #     cat script.log
      #     exit $res
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.TEAM_GITHUB_TOKEN }}
      #     ADO_TOKEN: ${{ secrets.ADO_TOKEN }}

      - name: create-pr
        run: |
          # SCRIPT_OUTPUT=$(cat script.log)
          # rm script.log

          git add .
          git commit -m "ci(${TARGET_ENV}): promote services (${STORY})"
          git push origin $NEW_BRANCH

          gh pr create --base main --head $NEW_BRANCH --title "ci(${TARGET_ENV}): promote services (${STORY})" --body "Promote ${SERVICES} to ${TARGET_ENV}
          Triggered by: ${{ github.actor }}
          # Script output:
          # ${SCRIPT_OUTPUT}"
        env:
          GH_TOKEN: ${{ github.token }}
